# Generated by Django 3.1 on 2020-08-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0002_auto_20200804_1722'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='privacy_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='door.privacy'),
        ),
    ]
