# Generated by Django 3.1 on 2020-08-04 16:19

from django.db import migrations
import door.models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0003_auto_20200804_1740'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', door.models.UserManager()),
            ],
        ),
    ]
