# Generated by Django 3.1 on 2020-08-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0005_auto_20200807_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy',
            name='disable_account',
            field=models.DateField(default=None, null=True),
        ),
    ]
