# Generated by Django 3.1 on 2020-08-14 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0006_privacy_disable_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privacy_settings',
        ),
        migrations.AddField(
            model_name='privacy',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.IntegerField(choices=[(0, 'Dev Mode'), (1, 'Unsplash Random')], default=0),
        ),
    ]
