# Generated by Django 3.1 on 2020-08-14 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0007_auto_20200814_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='disable_account',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
