# Generated by Django 3.1 on 2020-08-07 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=63)),
                ('description', models.TextField(default='', max_length=2087)),
                ('readme', models.TextField(max_length=2047, null=True)),
                ('script_js', models.FileField(null=True, upload_to='scripts_js/')),
                ('style_css', models.FileField(upload_to='styles_css/')),
                ('private_post', models.BooleanField(default=False)),
                ('number_of_like', models.BigIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('like', models.BooleanField(default=True)),
                ('like_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.tablepost')),
            ],
        ),
        migrations.CreateModel(
            name='TableComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1023)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.tablepost')),
            ],
        ),
    ]
