# Generated by Django 3.1 on 2020-08-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepost',
            name='description',
            field=models.TextField(default='', max_length=2047),
        ),
    ]
