# Generated by Django 3.1 on 2020-08-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20200810_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepost',
            name='script_js',
            field=models.TextField(blank=True, max_length=4095, null=True),
        ),
    ]
