# Generated by Django 3.1 on 2020-08-14 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0004_auto_20200814_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelike',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='tablelike',
            unique_together={('like_from', 'post')},
        ),
    ]
