# Generated by Django 3.1 on 2020-08-24 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0005_auto_20200814_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_like_set', to='table.tablepost'),
        ),
        migrations.AlterField(
            model_name='tablepost',
            name='user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
